export const challenges = [
  {
    title: "QR Code",
    link: "challenges/qr-code",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/qr-code/preview.png",
  },
  {
    title: "Blog preview card",
    link: "challenges/blog-preview-card",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/blog-preview-card/preview.png",
  },
  {
    title: "Social Links",
    link: "challenges/social-links",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/social-links/preview.png",
  },
  {
    title: "Recipe page",
    link: "challenges/recipe-page",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/recipe-page/preview.png",
  },
  {
    title: "Product card",
    link: "challenges/product-card",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/product-card/preview.png",
  },
  {
    title: "Card feature",
    link: "challenges/card-feature",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/card-feature/preview.png",
  },
  {
    title: "Testimonials grid section",
    link: "challenges/testimonials-grid-section",
    difficulty: 2,
    difficultyText: "Junior",
    image: "/testimonials-grid-section/preview.png",
  },
  {
    title: "Result component",
    link: "challenges/result-summary-component",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/result-summary-component/preview.png",
  },
  {
    title: "FAQ Accordion",
    link: "/challenges/faq-accordion-main",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/faq-accordion-main/preview.png",
  },
  {
    title: "Interactive rating",
    link: "/challenges/interactive-rating-component",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/interactive-rating-component/preview.png",
  },
  {
    title: "NFT card",
    link: "/challenges/nft-card",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/nft-card/preview.png",
  },
  {
    title: "Order summary",
    link: "/challenges/order-summary",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/order-summary/preview.png",
  },
  {
    title: "Stats Preview",
    link: "/challenges/stats-preview",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/stats-preview/preview.png",
  },
  {
    title: "3 Column card",
    link: "/challenges/3-column-card",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/3-column-card/preview.png",
  },
  {
    title: "Profile card",
    link: "/challenges/profile-card",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/profile-card/preview.png",
  },
  {
    title: "Social proof section",
    link: "/challenges/social-proof-section",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/social-proof-section/preview.png",
  },
  {
    title: "Article component",
    link: "/challenges/article-component",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/article-component/preview.png",
  },
  {
    title: "Base Apparel",
    link: "/challenges/base-apparel",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/base-apparel/preview.png",
  },
  {
    title: "Signup Form",
    link: "/challenges/signup-form",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/signup-form/preview.png",
  },
  {
    title: "Single price grid",
    link: "/challenges/single-price-grid",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/single-price-grid/preview.png",
  },
  {
    title: "Ping coming soon",
    link: "/challenges/ping-coming-soon",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/ping-coming-soon/preview.png",
  },
  {
    title: "Huddle landing page",
    link: "/challenges/huddle-landing-page",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/huddle-landing-page/preview.png",
  },
  {
    title: "Product List Cart",
    link: "/challenges/product-list-cart",
    difficulty: 2,
    difficultyText: "Junior",
    image: "/product-list-cart/preview.png",
  },
  {
    title: "Mortgage Repayment",
    link: "/challenges/mortgage-repayment-calculator",
    difficulty: 2,
    difficultyText: "Junior",
    image: "/mortgage-repayment-calculator/preview.png",
  },
  {
    title: "Contact Form",
    link: "/challenges/contact-form",
    difficulty: 2,
    difficultyText: "Junior",
    image: "/contact-form/preview.png",
  },
  {
    title: "Newsletter Sign Up",
    link: "/challenges/newsletter-sign-up",
    difficulty: 2,
    difficultyText: "Junior",
    image: "/newsletter-sign-up/preview.png",
  },
  {
    title: "Age Calculator",
    link: "/challenges/age-calculator",
    difficulty: 2,
    difficultyText: "Junior",
    image: "/age-calculator/preview.png",
  },
  {
    title: "News Homepage",
    link: "/challenges/news-homepage",
    difficulty: 2,
    difficultyText: "Junior",
    image: "/news-homepage/preview.png",
  },
]
