export const challenges = [
  {
    title: "QR Code",
    link: "challenges/qr-code",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/qr-code/preview.png",
  },
  {
    title: "Blog preview card",
    link: "challenges/blog-preview-card",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/blog-preview-card/preview.png",
  },
  {
    title: "Social Links",
    link: "challenges/social-links",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/social-links/preview.png",
  },
  {
    title: "Recipe page",
    link: "challenges/recipe-page",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/recipe-page/preview.png",
  },
  {
    title: "Product card",
    link: "challenges/product-card",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/product-card/preview.png",
  },
  {
    title: "Card feature",
    link: "challenges/card-feature",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/card-feature/preview.png",
  },
  {
    title: "Testimonials grid section",
    link: "challenges/testimonials-grid-section",
    difficulty: 2,
    difficultyText: "Junior",
    image: "/testimonials-grid-section/preview.png",
  },
  {
    title: "Result component",
    link: "challenges/result-summary-component",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/result-summary-component/preview.png",
  },
  {
    title: "FAQ Accordion",
    link: "/challenges/faq-accordion-main",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/faq-accordion-main/preview.png",
  },
  {
    title: "Interactive rating",
    link: "/challenges/interactive-rating-component",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/interactive-rating-component/preview.png",
  },
  {
    title: "NFT card",
    link: "/challenges/nft-card",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/nft-card/preview.png",
  },
  {
    title: "Order summary",
    link: "/challenges/order-summary",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/order-summary/preview.png",
  },
  {
    title: "Stats Preview",
    link: "/challenges/stats-preview",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/stats-preview/preview.png",
  },
  {
    title: "3 Column card",
    link: "/challenges/3-column-card",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/3-column-card/preview.png",
  },
  {
    title: "Profile card",
    link: "/challenges/profile-card",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/profile-card/preview.png",
  },
  {
    title: "Social proof section",
    link: "/challenges/social-proof-section",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/social-proof-section/preview.png",
  },
  {
    title: "Article component",
    link: "/challenges/article-component",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/article-component/preview.png",
  },
  {
    title: "Base Apparel coming soon",
    link: "/challenges/base-apparel",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/base-apparel/preview.png",
  },
]
