export const challenges = [
  {
    title: "QR Code",
    link: "challenges/qr-code",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/qr-code/preview.png",
  },
  {
    title: "Blog preview card",
    link: "challenges/blog-preview-card",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/blog-preview-card/preview.png",
  },
  {
    title: "Social Links",
    link: "challenges/social-links",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/social-links/preview.png",
  },
  {
    title: "Recipe page",
    link: "challenges/recipe-page",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/recipe-page/preview.png",
  },
  {
    title: "Product card",
    link: "challenges/product-card",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/product-card/preview.png",
  },
  {
    title: "Card feature",
    link: "challenges/card-feature",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/card-feature/preview.png",
  },
  {
    title: "Testimonials grid section",
    link: "challenges/testimonials-grid-section",
    difficulty: 2,
    difficultyText: "Junior",
    image: "/testimonials-grid-section/preview.png",
  },
  {
    title: "Result component",
    link: "challenges/result-summary-component",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/result-summary-component/preview.png",
  },
  {
    title: "FAQ Accordion",
    link: "/challenges/faq-accordion-main",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/faq-accordion-main/preview.png",
  },
  {
    title: "Interactive rating",
    link: "/challenges/interactive-rating-component",
    difficulty: 1,
    difficultyText: "Newbie",
    image: "/interactive-rating-component/preview.png",
  },
]
